name: dmnelf_preproc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - mne
  - nilearn
  - nibabel
  - pip
  - pip:
    - neurokit2
    - paramiko
    - joblib
