# 00b_extract_personal_masks.py
# Run locally: python 00b_extract_personal_masks.py
# Deploys cluster script, submits SLURM job.
#
# Adapted from pineuro mask_extraction.py (ICA-based pipeline).
# Key adaptations:
#   - fMRIPrep BOLD already in MNI → skip ANTs registration
#   - Use fMRIPrep brain mask during CanICA
#   - Vectorized spatial correlation inside brain mask only
#   - Z-score before combining components (equal contribution)
#   - Combine top 2 per network for bilateral coverage
#   - Yeo-7 (not Yeo-17): single unambiguous DMN and CEN labels
#   - CEN spatial constraint: skip midline posterior (PCC/precuneus)
#
# Yeo-7 labels:
#   DMN: Default = 7
#   CEN: Frontoparietal = 6
#
# Output per subject:
#   derivatives/network_masks/{subject}/
#     {subject}_space-MNI152NLin6Asym_res-2_dmn_mask.nii.gz
#     {subject}_space-MNI152NLin6Asym_res-2_cen_mask.nii.gz
#     {subject}_space-MNI152NLin6Asym_res-2_parcel_weights.json

import py_compile
import time
from pathlib import Path
from utils import run_ssh, scp_to, make_cluster_dirs
from config import (
    CLUSTER_BASE, SLURM_ACCOUNT, PYTHON,
    SUBJECTS, LOCAL_BASE
)

FMRIPREP_ROOT = "/projects/swglab/data/DMNELF/derivatives/fmriprep_25.2.5_fmap"
DIFUMO_CACHE  = "/projects/swglab/software/nilearn_data"
MASKS_ROOT    = "/projects/swglab/data/DMNELF/derivatives/network_masks"

# ── 1. Build cluster-side script ───────────────────────────
lines = [
    '#!/usr/bin/env python3',
    '"""',
    '00b_extract_personal_masks_cluster.py',
    'Adapted from pineuro mask_extraction.py.',
    'Extract personalized DMN/CEN masks via CanICA + Yeo-7 correlation.',
    'Uses Yeo-7 single labels for unambiguous DMN/CEN reference:',
    '  DMN: Default network = label 7',
    '  CEN: Frontoparietal network = label 6',
    'fMRIPrep BOLD already in MNI space — no ANTs registration needed.',
    'CEN spatial constraint: skip midline posterior components (PCC).',
    '"""',
    'import sys',
    'sys.stdout.reconfigure(line_buffering=True)',
    'import numpy as np',
    'import json',
    'from pathlib import Path',
    'import os',
    'import warnings',
    'import nibabel as nib',
    'import matplotlib',
    'matplotlib.use("Agg")  # non-interactive backend for cluster',
    'import matplotlib.pyplot as plt',
    'from matplotlib.colors import LinearSegmentedColormap as _LSC',
    'from nilearn import plotting',
    '# Solid bright colors: DMN=blue, CEN=red',
    '_CMAP_DMN = _LSC.from_list("dmn", ["#0077FF", "#0077FF"])',
    '_CMAP_CEN = _LSC.from_list("cen", ["#FF1A00", "#FF1A00"])',
    '',
    '# ── Paths ─────────────────────────────────────────────',
    'FMRIPREP_ROOT = Path("' + FMRIPREP_ROOT + '")',
    'MASKS_ROOT    = Path("' + MASKS_ROOT + '")',
    'DIFUMO_CACHE  = Path("' + DIFUMO_CACHE + '")',
    'MASKS_ROOT.mkdir(parents=True, exist_ok=True)',
    'os.environ["NILEARN_DATA"] = str(DIFUMO_CACHE)',
    '',
    'SUBJECTS = ' + str(SUBJECTS),
    '',
    '# Parameters',
    'N_COMPONENTS  = 35   # matching real-time pipeline (Bloom 2023)',
    'N_VOXELS_MASK = 2000 # top N voxels per mask',
    '',
    '# Yeo-7 labels (unambiguous single-label DMN and CEN)',
    '# Label 7 = Default network (PCC + mPFC + angular gyrus)',
    '# Label 6 = Frontoparietal network (IPS + dlPFC bilateral)',
    'YEO_DMN_LABEL = 7',
    'YEO_CEN_LABEL = 6',
    '',
    '# CEN spatial constraint: exclude midline posterior components',
    '# PCC/precuneus signature: |x| < 15mm AND y < -45mm',
    'CEN_EXCL_X = 15.0',
    'CEN_EXCL_Y = -45.0',
    '',
    '# ── Load atlases ──────────────────────────────────────',
    'print("=" * 55)',
    'print("Loading atlases")',
    'print("=" * 55)',
    'from nilearn import datasets',
    'with warnings.catch_warnings():',
    '    warnings.simplefilter("ignore")',
    '    yeo = datasets.fetch_atlas_yeo_2011(n_networks=7, thickness="thick")',
    'yeo_path = yeo.maps',
    'print("Yeo atlas_type: " + str(getattr(yeo, "atlas_type", "N/A")))',
    'print("Yeo labels:     " + str(getattr(yeo, "labels", "N/A")))',
    'yeo_img  = nib.load(yeo_path)',
    'yeo_data = np.squeeze(yeo_img.get_fdata()).astype(np.int32)',
    'print("Yeo-7 shape: " + str(yeo_data.shape))',
    '',
    'yeo_dmn = (yeo_data == YEO_DMN_LABEL).astype(np.float32)',
    'yeo_cen = (yeo_data == YEO_CEN_LABEL).astype(np.float32)',
    'print("Yeo-7 DMN voxels (label 7): " + str(int(yeo_dmn.sum())))',
    'print("Yeo-7 CEN voxels (label 6): " + str(int(yeo_cen.sum())))',
    '',
    'difumo = datasets.fetch_atlas_difumo(',
    '    dimension=64, resolution_mm=2,',
    '    data_dir=str(DIFUMO_CACHE)',
    ')',
    'difumo_maps = difumo.maps if hasattr(difumo, "maps") else difumo["maps"]',
    'difumo_img  = nib.load(difumo_maps)',
    'print("DiFuMo-64 shape: " + str(difumo_img.shape))',
    '',
    '# ── Helpers ───────────────────────────────────────────',
    'def resample_to(source_img, target_img, interpolation="nearest"):',
    '    from nilearn.image import resample_to_img',
    '    with warnings.catch_warnings():',
    '        warnings.simplefilter("ignore")',
    '        return resample_to_img(',
    '            source_img, target_img,',
    '            interpolation=interpolation',
    '        )',
    '',
    'def spatial_corr_masked(X_masked, ref_mask_flat):',
    '    """',
    '    Vectorized spatial correlation of all ICA components',
    '    against a binary reference map, inside brain mask only.',
    '    Adapted from pineuro spatial_correlation().',
    '    X_masked:       (V, n_comp)',
    '    ref_mask_flat:  (V,)',
    '    Returns: (n_comp,)',
    '    """',
    '    X_dm   = X_masked - X_masked.mean(axis=0, keepdims=True)',
    '    x_norm = np.sqrt((X_dm**2).sum(axis=0))',
    '    y      = ref_mask_flat.astype(np.float64)',
    '    y_dm   = y - y.mean()',
    '    y_norm = np.sqrt((y_dm**2).sum())',
    '    if y_norm < 1e-10:',
    '        return np.zeros(X_masked.shape[1])',
    '    num   = X_dm.T @ y_dm',
    '    denom = x_norm * y_norm',
    '    denom[denom < 1e-10] = 1e-10',
    '    return num / denom',
    '',
    'def zscore_combine(c1, c2):',
    '    """',
    '    Z-score each component then average.',
    '    Adapted from pineuro combine_ica_components().',
    '    Ensures equal contribution regardless of value range.',
    '    """',
    '    def zs(x):',
    '        s = x.std()',
    '        return (x - x.mean()) / s if s > 0 else x - x.mean()',
    '    return (zs(c1) + zs(c2)) / 2.0',
    '',
    'def top_n_mask(component, n_voxels, affine):',
    '    """Binary mask of top N positive voxels."""',
    '    flat = component.ravel()',
    '    pos  = np.where(flat > 0)[0]',
    '    if len(pos) <= n_voxels:',
    '        binary = (flat > 0).astype(np.uint8).reshape(component.shape)',
    '    else:',
    '        top    = np.argpartition(flat[pos], -n_voxels)[-n_voxels:]',
    '        result = np.zeros_like(flat, dtype=np.uint8)',
    '        result[pos[top]] = 1',
    '        binary = result.reshape(component.shape)',
    '    return nib.Nifti1Image(binary, affine)',
    '',
    'def get_centroid_mni(ic, components, aff, n_top=500):',
    '    """MNI centroid of top N absolute-value voxels of component ic."""',
    '    comp   = components[..., ic]',
    '    thresh = np.sort(np.abs(comp).ravel())[-n_top]',
    '    xi, yi, zi = np.where(np.abs(comp) >= thresh)',
    '    cx = float(xi.mean() * aff[0, 0] + aff[0, 3])',
    '    cy = float(yi.mean() * aff[1, 1] + aff[1, 3])',
    '    cz = float(zi.mean() * aff[2, 2] + aff[2, 3])',
    '    return cx, cy, cz',
    '',
    'def is_midline_posterior(ic, components, aff):',
    '    """',
    '    True if component centroid is midline posterior.',
    '    Flags PCC/precuneus leaking into CEN selection.',
    '    Criterion: |x| < 15mm AND y < -45mm',
    '    """',
    '    cx, cy, cz = get_centroid_mni(ic, components, aff)',
    '    return abs(cx) < CEN_EXCL_X and cy < CEN_EXCL_Y',
    '',
    'def check_laterality(mask_img, label):',
    '    data = mask_img.get_fdata()',
    '    aff  = mask_img.affine',
    '    xi, yi, zi = np.where(data > 0)',
    '    mx = xi * aff[0, 0] + aff[0, 3]',
    '    print("  " + label + ":"',
    '          + "  L=" + str(int((mx < 0).sum()))',
    '          + "  R=" + str(int((mx > 0).sum())))',
    '',
    '# ── Main loop ─────────────────────────────────────────',
    'print()',
    'print("=" * 55)',
    'print("Extracting personalized masks")',
    'print("=" * 55)',
    '',
    'for subject in SUBJECTS:',
    '    print()',
    '    print("--- " + subject + " ---")',
    '',
    '    sub_dir = MASKS_ROOT / subject',
    '    sub_dir.mkdir(parents=True, exist_ok=True)',
    '',
    '    prefix      = subject + "_space-MNI152NLin6Asym_res-2"',
    '    out_dmn     = sub_dir / (prefix + "_dmn_mask.nii.gz")',
    '    out_cen     = sub_dir / (prefix + "_cen_mask.nii.gz")',
    '    out_weights = sub_dir / (prefix + "_parcel_weights.json")',
    '',
    '    out_png = sub_dir / (prefix + "_masks.png")',
    '    if out_dmn.exists() and out_cen.exists() and out_weights.exists():',
    '        if out_png.exists():',
    '            print("  EXISTS (skip): " + subject)',
    '            continue',
    '        # masks exist but PNG missing — generate from saved files',
    '        print("  EXISTS: generating missing PNG for " + subject)',
    '        with open(str(out_weights)) as f:',
    '            w = json.load(f)',
    '        dmn_mask = nib.load(str(out_dmn))',
    '        cen_mask = nib.load(str(out_cen))',
    '        _dmn_c1 = w["dmn_ica_component1"]',
    '        _dmn_c2 = w["dmn_ica_component2"]',
    '        _cen_c1 = w["cen_ica_component1"]',
    '        _cen_c2 = w["cen_ica_component2"]',
    '        _r_d1   = w["dmn_yeo_corr1"]',
    '        _r_d2   = w["dmn_yeo_corr2"]',
    '        _r_c1   = w["cen_yeo_corr1"]',
    '        _r_c2   = w["cen_yeo_corr2"]',
    '        fig = plt.figure(figsize=(16, 10))',
    '        fig.suptitle(',
    '            subject + "  |  DMN (blue)  CEN (red)"',
    '            + "\\nDMN ICs: " + str(_dmn_c1) + "," + str(_dmn_c2)',
    '            + "   r=" + "{:.2f}".format(_r_d1)',
    '            + "," + "{:.2f}".format(_r_d2)',
    '            + "   CEN ICs: " + str(_cen_c1) + "," + str(_cen_c2)',
    '            + "   r=" + "{:.2f}".format(_r_c1)',
    '            + "," + "{:.2f}".format(_r_c2),',
    '            fontsize=10, fontweight="bold"',
    '        )',
    '        ax0 = fig.add_axes([0.0, 0.52, 1.0, 0.44])',
    '        disp0 = plotting.plot_glass_brain(',
    '            None, axes=ax0, figure=fig,',
    '            title="Glass brain: DMN (red) + CEN (blue)",',
    '            display_mode="lyrz", plot_abs=False',
    '        )',
    '        disp0.add_overlay(dmn_mask, cmap=_CMAP_DMN, alpha=1.0)',
    '        disp0.add_overlay(cen_mask, cmap=_CMAP_CEN, alpha=0.9)',
    '        ax1 = fig.add_axes([0.0, 0.02, 0.5, 0.44])',
    '        plotting.plot_roi(',
    '            dmn_mask, axes=ax1, figure=fig,',
    '            title="DMN \u2014 axial slices", cmap=_CMAP_DMN,',
    '            display_mode="z", cut_coords=7',
    '        )',
    '        ax2 = fig.add_axes([0.5, 0.02, 0.5, 0.44])',
    '        plotting.plot_roi(',
    '            cen_mask, axes=ax2, figure=fig,',
    '            title="CEN \u2014 axial slices", cmap=_CMAP_CEN,',
    '            display_mode="z", cut_coords=7',
    '        )',
    '        plt.savefig(str(out_png), dpi=150, bbox_inches="tight")',
    '        plt.close(fig)',
    '        print("  Saved: " + str(out_png.name))',
    '        continue',
    '',
    '    # ── Load BOLD and brain mask ───────────────────────',
    '    bold_name = (subject',
    '                 + "_ses-dmnelf_task-rest_run-01"',
    '                 + "_space-MNI152NLin6Asym_res-2"',
    '                 + "_desc-preproc_bold.nii.gz")',
    '    bold_path = (FMRIPREP_ROOT / subject / "ses-dmnelf"',
    '                 / "func" / bold_name)',
    '',
    '    mask_name = (subject',
    '                 + "_ses-dmnelf_task-rest_run-01"',
    '                 + "_space-MNI152NLin6Asym_res-2"',
    '                 + "_desc-brain_mask.nii.gz")',
    '    mask_path = (FMRIPREP_ROOT / subject / "ses-dmnelf"',
    '                 / "func" / mask_name)',
    '',
    '    if not bold_path.exists():',
    '        print("  MISSING BOLD: " + bold_name)',
    '        continue',
    '',
    '    if not mask_path.exists():',
    '        anat_mask = (FMRIPREP_ROOT / subject / "ses-dmnelf"',
    '                     / "anat" / (subject',
    '                     + "_ses-dmnelf_space-MNI152NLin6Asym_res-2"',
    '                     + "_desc-brain_mask.nii.gz"))',
    '        if anat_mask.exists():',
    '            mask_path = anat_mask',
    '            print("  Using anat brain mask")',
    '        else:',
    '            mask_path = None',
    '            print("  WARNING: no brain mask found")',
    '',
    '    print("  BOLD: " + bold_name)',
    '',
    '    # ── CanICA with brain mask ─────────────────────────',
    '    from nilearn.decomposition import CanICA',
    '    canica_kwargs = dict(',
    '        n_components=N_COMPONENTS,',
    '        memory=str(DIFUMO_CACHE / "nilearn_cache"),',
    '        memory_level=2,',
    '        random_state=42,',
    '        standardize=True,',
    '        n_jobs=-1,',
    '        verbose=0',
    '    )',
    '    if mask_path is not None:',
    '        canica_kwargs["mask"] = str(mask_path)',
    '    canica = CanICA(**canica_kwargs)',
    '    print("  Running CanICA (" + str(N_COMPONENTS) + " components)...")',
    '    canica.fit([str(bold_path)])',
    '    components_img = canica.components_img_',
    '    components     = components_img.get_fdata()  # (x,y,z,n_comp)',
    '    aff            = components_img.affine',
    '    print("  Components shape: " + str(components.shape))',
    '',
    '    # ── Resample Yeo-7 to BOLD space ──────────────────',
    '    yeo_dmn_r = np.squeeze(resample_to(',
    '        nib.Nifti1Image(yeo_dmn, yeo_img.affine),',
    '        components_img',
    '    ).get_fdata())',
    '    yeo_cen_r = np.squeeze(resample_to(',
    '        nib.Nifti1Image(yeo_cen, yeo_img.affine),',
    '        components_img',
    '    ).get_fdata())',
    '',
    '    print("  Yeo-7 DMN voxels in BOLD space: "',
    '          + str(int((yeo_dmn_r > 0).sum())))',
    '    print("  Yeo-7 CEN voxels in BOLD space: "',
    '          + str(int((yeo_cen_r > 0).sum())))',
    '',
    '    # ── Brain mask for correlation ─────────────────────',
    '    brain_mask = (np.abs(components).sum(axis=-1) > 0)',
    '    V = brain_mask.sum()',
    '    print("  Brain mask voxels: " + str(int(V)))',
    '',
    '    X_masked       = components[brain_mask]    # (V, n_comp)',
    '    yeo_dmn_masked = yeo_dmn_r[brain_mask]     # (V,)',
    '    yeo_cen_masked = yeo_cen_r[brain_mask]     # (V,)',
    '',
    '    # ── Vectorized spatial correlations ───────────────',
    '    corr_dmn = spatial_corr_masked(X_masked, yeo_dmn_masked)',
    '    corr_cen = spatial_corr_masked(X_masked, yeo_cen_masked)',
    '',
    '    dmn_sorted = np.abs(corr_dmn).argsort()[::-1]',
    '    cen_sorted = np.abs(corr_cen).argsort()[::-1]',
    '',
    '    print("  Top 5 DMN correlations:")',
    '    for i in dmn_sorted[:5]:',
    '        cx, cy, cz = get_centroid_mni(int(i), components, aff)',
    '        print("    IC" + str(i)',
    '              + "  r=" + "{:+.3f}".format(corr_dmn[i])',
    '              + "  ctr=(" + str(round(cx,0))',
    '              + "," + str(round(cy,0))',
    '              + "," + str(round(cz,0)) + ")")',
    '',
    '    print("  Top 5 CEN correlations:")',
    '    for i in cen_sorted[:5]:',
    '        cx, cy, cz = get_centroid_mni(int(i), components, aff)',
    '        midline = is_midline_posterior(int(i), components, aff)',
    '        flag = " [SKIP:PCC]" if midline else ""',
    '        print("    IC" + str(i)',
    '              + "  r=" + "{:+.3f}".format(corr_cen[i])',
    '              + "  ctr=(" + str(round(cx,0))',
    '              + "," + str(round(cy,0))',
    '              + "," + str(round(cz,0)) + ")"',
    '              + flag)',
    '',
    '    # ── Select DMN: top 2 by absolute correlation ─────',
    '    # Yeo-7 Default covers full DMN (PCC+mPFC) in one label',
    '    # so top-2 should naturally capture both subregions',
    '    dmn_comp  = int(dmn_sorted[0])',
    '    dmn_comp2 = int(dmn_sorted[1])',
    '    used      = {dmn_comp, dmn_comp2}',
    '',
    '    # ── Select CEN: skip midline posterior (PCC leak) ─',
    '    cen_comp  = None',
    '    cen_comp2 = None',
    '    skipped   = []',
    '',
    '    for ic in cen_sorted:',
    '        ic = int(ic)',
    '        if ic in used:',
    '            continue',
    '        dmn_contaminated = abs(corr_dmn[ic]) > 0.5 * abs(corr_cen[ic])',
    '        if is_midline_posterior(ic, components, aff) or dmn_contaminated:',
    '            cx, cy, cz = get_centroid_mni(ic, components, aff)',
    '            reason = "PCC" if is_midline_posterior(ic, components, aff) else "DMN-overlap"',
    '            skipped.append("IC" + str(ic)',
    '                           + " [" + reason + "]"',
    '                           + " (x=" + str(round(cx,1))',
    '                           + " y=" + str(round(cy,1)) + ")"',
    '                           + " r_dmn=" + "{:.2f}".format(corr_dmn[ic])',
    '                           + " r_cen=" + "{:.2f}".format(corr_cen[ic]))',
    '            continue',
    '        if cen_comp is None:',
    '            cen_comp = ic',
    '            used.add(ic)',
    '        elif cen_comp2 is None:',
    '            cen_comp2 = ic',
    '            used.add(ic)',
    '            break',
    '',
    '    if skipped:',
    '        print("  Skipped PCC components: " + ", ".join(skipped))',
    '',
    '    # Fallback if constraint too aggressive',
    '    if cen_comp is None or cen_comp2 is None:',
    '        print("  WARNING: CEN fallback — relaxing constraint")',
    '        for ic in cen_sorted:',
    '            ic = int(ic)',
    '            if ic not in used:',
    '                if cen_comp is None:',
    '                    cen_comp = ic',
    '                    used.add(ic)',
    '                elif cen_comp2 is None:',
    '                    cen_comp2 = ic',
    '                    used.add(ic)',
    '                    break',
    '',
    '    cx1,cy1,cz1 = get_centroid_mni(dmn_comp,  components, aff)',
    '    cx2,cy2,cz2 = get_centroid_mni(dmn_comp2, components, aff)',
    '    cx3,cy3,cz3 = get_centroid_mni(cen_comp,  components, aff)',
    '    cx4,cy4,cz4 = get_centroid_mni(cen_comp2, components, aff)',
    '    print("  Selected DMN IC1: IC" + str(dmn_comp)',
    '          + "  r=" + "{:+.3f}".format(corr_dmn[dmn_comp])',
    '          + "  ctr=(" + str(round(cx1,0)) + "," + str(round(cy1,0)) + "," + str(round(cz1,0)) + ")")',
    '    print("  Selected DMN IC2: IC" + str(dmn_comp2)',
    '          + "  r=" + "{:+.3f}".format(corr_dmn[dmn_comp2])',
    '          + "  ctr=(" + str(round(cx2,0)) + "," + str(round(cy2,0)) + "," + str(round(cz2,0)) + ")")',
    '    print("  Selected CEN IC1: IC" + str(cen_comp)',
    '          + "  r=" + "{:+.3f}".format(corr_cen[cen_comp])',
    '          + "  ctr=(" + str(round(cx3,0)) + "," + str(round(cy3,0)) + "," + str(round(cz3,0)) + ")")',
    '    print("  Selected CEN IC2: IC" + str(cen_comp2)',
    '          + "  r=" + "{:+.3f}".format(corr_cen[cen_comp2])',
    '          + "  ctr=(" + str(round(cx4,0)) + "," + str(round(cy4,0)) + "," + str(round(cz4,0)) + ")")',
    '',
    '    # ── Sign-correct then z-score combine ─────────────',
    '    dmn_c1 = components[..., dmn_comp].copy()',
    '    dmn_c2 = components[..., dmn_comp2].copy()',
    '    cen_c1 = components[..., cen_comp].copy()',
    '    cen_c2 = components[..., cen_comp2].copy()',
    '',
    '    if corr_dmn[dmn_comp] < 0:',
    '        dmn_c1 = -dmn_c1',
    '        print("  Flipped DMN IC1")',
    '    if corr_dmn[dmn_comp2] < 0:',
    '        dmn_c2 = -dmn_c2',
    '        print("  Flipped DMN IC2")',
    '    if corr_cen[cen_comp] < 0:',
    '        cen_c1 = -cen_c1',
    '        print("  Flipped CEN IC1")',
    '    if corr_cen[cen_comp2] < 0:',
    '        cen_c2 = -cen_c2',
    '        print("  Flipped CEN IC2")',
    '',
    '    dmn_combined = zscore_combine(dmn_c1, dmn_c2)',
    '    cen_combined = zscore_combine(cen_c1, cen_c2)',
    '',
    '    # ── Threshold to top N voxels ─────────────────────',
    '    dmn_mask = top_n_mask(dmn_combined, N_VOXELS_MASK, aff)',
    '    cen_mask = top_n_mask(cen_combined, N_VOXELS_MASK, aff)',
    '',
    '    check_laterality(dmn_mask, "DMN")',
    '    check_laterality(cen_mask, "CEN")',
    '',
    '    # ── DiFuMo parcel overlap weights ─────────────────',
    '    difumo_r = resample_to(',
    '        difumo_img, components_img,',
    '        interpolation="linear"',
    '    ).get_fdata()  # (x,y,z,64)',
    '',
    '    dmn_flat    = dmn_mask.get_fdata().ravel()',
    '    cen_flat    = cen_mask.get_fdata().ravel()',
    '    dmn_weights = np.zeros(64)',
    '    cen_weights = np.zeros(64)',
    '    for p in range(64):',
    '        parcel         = difumo_r[..., p].ravel()',
    '        dmn_weights[p] = float((parcel * dmn_flat).sum())',
    '        cen_weights[p] = float((parcel * cen_flat).sum())',
    '',
    '    if dmn_weights.sum() > 0:',
    '        dmn_weights = dmn_weights / dmn_weights.sum()',
    '    if cen_weights.sum() > 0:',
    '        cen_weights = cen_weights / cen_weights.sum()',
    '',
    '    dmn_top8 = np.argsort(dmn_weights)[::-1][:8].tolist()',
    '    cen_top6 = np.argsort(cen_weights)[::-1][:6].tolist()',
    '',
    '    print("  Top DMN parcels (personal): " + str(dmn_top8))',
    '    print("  Group DMN parcels:          [3,6,22,29,35,38,58,60]")',
    '    print("  Top CEN parcels (personal): " + str(cen_top6))',
    '    print("  Group CEN parcels:          [4,31,47,48,50,51]")',
    '',
    '    # ── Save masks ────────────────────────────────────',
    '    nib.save(dmn_mask, str(out_dmn))',
    '    nib.save(cen_mask, str(out_cen))',
    '    print("  Saved: " + str(out_dmn.name))',
    '    print("  Saved: " + str(out_cen.name))',
    '',
    '    # ── Save weights JSON ─────────────────────────────',
    '    weights_dict = {',
    '        "subject":             subject,',
    '        "dmn_weights":         dmn_weights.tolist(),',
    '        "cen_weights":         cen_weights.tolist(),',
    '        "dmn_top8":            dmn_top8,',
    '        "cen_top6":            cen_top6,',
    '        "dmn_ica_component1":  dmn_comp,',
    '        "dmn_ica_component2":  dmn_comp2,',
    '        "cen_ica_component1":  cen_comp,',
    '        "cen_ica_component2":  cen_comp2,',
    '        "dmn_yeo_corr1":       float(corr_dmn[dmn_comp]),',
    '        "dmn_yeo_corr2":       float(corr_dmn[dmn_comp2]),',
    '        "cen_yeo_corr1":       float(corr_cen[cen_comp]),',
    '        "cen_yeo_corr2":       float(corr_cen[cen_comp2]),',
    '        "group_dmn_idx":       [3,6,29,35,38,58,60,61],',
    '        "group_cen_idx":       [4,31,47,48,50,51],',
    '        "n_voxels_mask":       N_VOXELS_MASK,',
    '        "n_ica_components":    N_COMPONENTS,',
    '        "yeo_dmn_label":       YEO_DMN_LABEL,',
    '        "yeo_cen_label":       YEO_CEN_LABEL,',
    '        "cen_excl_x":          CEN_EXCL_X,',
    '        "cen_excl_y":          CEN_EXCL_Y,',
    '        "cen_skipped_pcc":     skipped,',
    '    }',
    '    with open(str(out_weights), "w") as f:',
    '        json.dump(weights_dict, f, indent=2)',
    '    print("  Saved: " + str(out_weights.name))',
    '',
    '    # ── Visualize masks ───────────────────────────────────',
    '    out_png = sub_dir / (prefix + "_masks.png")',
    '    fig = plt.figure(figsize=(16, 10))',
    '    fig.suptitle(',
    '        subject + "  |  DMN (blue)  CEN (red)"',
    '        + "\\nDMN ICs: " + str(dmn_comp) + "," + str(dmn_comp2)',
    '        + "   r=" + "{:.2f}".format(corr_dmn[dmn_comp])',
    '        + "," + "{:.2f}".format(corr_dmn[dmn_comp2])',
    '        + "   CEN ICs: " + str(cen_comp) + "," + str(cen_comp2)',
    '        + "   r=" + "{:.2f}".format(corr_cen[cen_comp])',
    '        + "," + "{:.2f}".format(corr_cen[cen_comp2]),',
    '        fontsize=10, fontweight="bold"',
    '    )',
    '    ax0 = fig.add_axes([0.0, 0.52, 1.0, 0.44])',
    '    disp0 = plotting.plot_glass_brain(',
    '        None, axes=ax0, figure=fig,',
    '        title="Glass brain: DMN (red) + CEN (blue)",',
    '        display_mode="lyrz", plot_abs=False',
    '    )',
    '    disp0.add_overlay(dmn_mask, cmap=_CMAP_DMN, alpha=1.0)',
    '    disp0.add_overlay(cen_mask, cmap=_CMAP_CEN, alpha=0.9)',
    '    ax1 = fig.add_axes([0.0, 0.02, 0.5, 0.44])',
    '    plotting.plot_roi(',
    '        dmn_mask, axes=ax1, figure=fig,',
    '        title="DMN \u2014 axial slices", cmap=_CMAP_DMN,',
    '        display_mode="z", cut_coords=7',
    '    )',
    '    ax2 = fig.add_axes([0.5, 0.02, 0.5, 0.44])',
    '    plotting.plot_roi(',
    '        cen_mask, axes=ax2, figure=fig,',
    '        title="CEN \u2014 axial slices", cmap=_CMAP_CEN,',
    '        display_mode="z", cut_coords=7',
    '    )',
    '    plt.savefig(str(out_png), dpi=150, bbox_inches="tight")',
    '    plt.close(fig)',
    '    print("  Saved: " + str(out_png.name))',
    '',
    '',
    '# ── Overview: all subjects side by side ─────────────────────',
    'print()',
    'print("=" * 55)',
    'print("Generating all-subjects overview PNG")',
    'print("=" * 55)',
    '',
    'out_overview = MASKS_ROOT / "all_subjects_masks_overview.png"',
    '',
    'subs_ok = []',
    'for subject in SUBJECTS:',
    '    sub_dir = MASKS_ROOT / subject',
    '    prefix  = subject + "_space-MNI152NLin6Asym_res-2"',
    '    p_dmn = sub_dir / (prefix + "_dmn_mask.nii.gz")',
    '    p_cen = sub_dir / (prefix + "_cen_mask.nii.gz")',
    '    if p_dmn.exists() and p_cen.exists():',
    '        subs_ok.append((subject, p_dmn, p_cen))',
    '',
    'if subs_ok:',
    '    n     = len(subs_ok)',
    '    row_h = 1.0 / n',
    '    fig_ov = plt.figure(figsize=(18, 3.0 * n))',
    '    fig_ov.suptitle(',
    '        "All subjects  |  DMN (blue)  CEN (red)",',
    '        fontsize=14, fontweight="bold"',
    '    )',
    '    for i, (subject, p_dmn, p_cen) in enumerate(subs_ok):',
    '        dmn_img = nib.load(str(p_dmn))',
    '        cen_img = nib.load(str(p_cen))',
    '        y_bot = (n - 1 - i) * row_h',
    '        pad   = 0.005',
    '        # glass brain with both masks: left 50%',
    '        ax_gb = fig_ov.add_axes([0.0, y_bot + pad, 0.50, row_h - 2 * pad])',
    '        disp = plotting.plot_glass_brain(',
    '            None, axes=ax_gb, figure=fig_ov,',
    '            display_mode="lyrz", plot_abs=False,',
    '            title=subject',
    '        )',
    '        disp.add_overlay(dmn_img, cmap=_CMAP_DMN, alpha=1.0)',
    '        disp.add_overlay(cen_img, cmap=_CMAP_CEN, alpha=0.9)',
    '        # DMN axial slices: middle 24%',
    '        ax_d = fig_ov.add_axes([0.51, y_bot + pad, 0.24, row_h - 2 * pad])',
    '        plotting.plot_roi(',
    '            dmn_img, axes=ax_d, figure=fig_ov,',
    '            title="DMN" if i == 0 else None,',
    '            cmap=_CMAP_DMN, display_mode="z", cut_coords=5',
    '        )',
    '        # CEN axial slices: right 24%',
    '        ax_c = fig_ov.add_axes([0.76, y_bot + pad, 0.24, row_h - 2 * pad])',
    '        plotting.plot_roi(',
    '            cen_img, axes=ax_c, figure=fig_ov,',
    '            title="CEN" if i == 0 else None,',
    '            cmap=_CMAP_CEN, display_mode="z", cut_coords=5',
    '        )',
    '    plt.savefig(str(out_overview), dpi=150, bbox_inches="tight")',
    '    plt.close(fig_ov)',
    '    print("  Saved: " + str(out_overview))',
    'else:',
    '    print("  No masks found — skipping overview")',
    '',
    'print()',
    'print("=" * 55)',
    'print("DONE")',
    'print("=" * 55)',
]

# ── 2. Save cluster script locally ─────────────────────────
script_name = "00b_extract_personal_masks_cluster.py"
script_path = LOCAL_BASE / "scripts" / script_name
script_path.parent.mkdir(parents=True, exist_ok=True)

with open(script_path, "w") as f:
    f.write("\n".join(lines))

# ── 3. Syntax check ────────────────────────────────────────
print("Checking syntax...")
try:
    py_compile.compile(str(script_path), doraise=True)
    print("Syntax OK: " + script_name)
except py_compile.PyCompileError as e:
    print("SYNTAX ERROR: " + str(e))
    raise

# ── 4. Build SLURM script ──────────────────────────────────
sbatch_lines = [
    "#!/bin/bash",
    "#SBATCH --job-name=personal_masks",
    "#SBATCH --output=" + CLUSTER_BASE + "/logs/personal_masks_%j.out",
    "#SBATCH --error="  + CLUSTER_BASE + "/logs/personal_masks_%j.err",
    "#SBATCH --partition=sharing",
    "#SBATCH --time=01:00:00",
    "#SBATCH --cpus-per-task=8",
    "#SBATCH --mem=64G",
    "#SBATCH --account=" + SLURM_ACCOUNT,
    "",
    PYTHON + " " + CLUSTER_BASE + "/scripts/" + script_name,
]

sbatch_name = "00b_extract_personal_masks.sh"
sbatch_path = LOCAL_BASE / "scripts" / sbatch_name
with open(sbatch_path, "w") as f:
    f.write("\n".join(sbatch_lines))

# ── 5. Deploy ──────────────────────────────────────────────
print("\nDeploying scripts...")
scp_to(script_path,
       CLUSTER_BASE + "/scripts/" + script_name,
       verbose=False)
scp_to(sbatch_path,
       CLUSTER_BASE + "/scripts/" + sbatch_name,
       verbose=False)
print("Deployed: " + script_name)
print("Deployed: " + sbatch_name)

# ── 6. Submit ──────────────────────────────────────────────
print("\nSubmitting SLURM job...")
result = run_ssh("sbatch " + CLUSTER_BASE + "/scripts/" + sbatch_name)
job_id = ""
for line in result.stdout.strip().split("\n"):
    if "Submitted" in line:
        job_id = line.strip().split()[-1]
        print("Job ID: " + job_id)

# ── 7. Monitor ─────────────────────────────────────────────
if job_id:
    print("\nMonitoring job " + job_id + "  (Ctrl+C to stop watching)")
    print("-" * 55)
    try:
        while True:
            r = run_ssh(
                "squeue -j " + job_id
                + " --format=%.8i_%.8T_%.10M 2>/dev/null",
                verbose=False
            )
            status = r.stdout.strip()
            if status and "JOBID" not in status.split("\n")[-1]:
                print(status)
            else:
                print("Job finished — checking log...")
                log = run_ssh(
                    "tail -60 " + CLUSTER_BASE
                    + "/logs/personal_masks_" + job_id + ".out 2>/dev/null",
                    verbose=False
                )
                print(log.stdout)
                break
            time.sleep(15)
    except KeyboardInterrupt:
        print("\nStopped watching. Check manually:")
        print("  squeue -j " + job_id)
        print("  tail -f " + CLUSTER_BASE
              + "/logs/personal_masks_" + job_id + ".out")