# 07_microstate_network_proxy.py
# Run locally: python deploy_scripts/07_microstate_network_proxy.py
# Deploys cluster script, submits SLURM job.
#
# What it does on the cluster:
#   For each subject × task × run load:
#     - TESS features (HRF-convolved, n_vols × 9, cols 0:7 = T-hat)
#     - Personal CEN_z / DMN_z (step 00d outputs, *_cen_z.npy, *_dmn_z.npy)
#     - DiFuMo CEN_z / DMN_z (re-extracted from TSV, same parcels as step 03)
#     - PDA_direct (step 00d, evaluation ground truth)
#
#   LORO CV per subject (feedback runs):
#     For source in [personal, difumo]:
#       ridge T-hat → CEN_z → w_CEN
#       ridge T-hat → DMN_z → w_DMN
#       microPDA = (w_CEN - w_DMN) · T-hat_test
#       r_microPDA_{source} = pearsonr(microPDA, pda_direct_test)
#     r_simple = pearsonr(T-hat_CEN - T-hat_DMN, pda_direct_test)  [baseline]
#
#   Also fits on all runs combined → group-average interpretable weights.
#
# Outputs (CLUSTER_BASE/results/network_proxy/):
#   network_proxy_weights_250Hz.csv    per-subject × source weights
#   network_proxy_correlations_250Hz.csv  LORO r per-subject × run × source
#   network_proxy_group_250Hz.png      4-panel summary figure

import sys
import py_compile
import time
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))
from utils import run_ssh, scp_to
from config import (
    CLUSTER_BASE, SLURM_ACCOUNT, PYTHON,
    SUBJECTS_EEG_FMRI_ALL, LOCAL_BASE,
    MISSING_RUNS, DMN_IDX, CEN_IDX,
    DIFUMO_ROOT,
)

lines = [
    '#!/usr/bin/env python3',
    '"""07_microstate_network_proxy_cluster.py',
    'Decomposed microstate network proxy: microCEN - microDMN = microPDA.',
    'Regresses all 7 T-hat maps onto CEN_z and DMN_z separately (ridge),',
    'then differences to form microPDA. Evaluates via LORO CV vs pda_direct.',
    'Two target sources compared: personal masks (step 00d) vs DiFuMo parcels.',
    '"""',
    'import sys',
    'sys.stdout.reconfigure(line_buffering=True)',
    'import numpy as np',
    'import pandas as pd',
    'import json, csv',
    'from pathlib import Path',
    'from scipy.stats import pearsonr',
    'import matplotlib',
    'matplotlib.use("Agg")',
    'import matplotlib.pyplot as plt',
    '',
    '# ── Paths ────────────────────────────────────────────',
    'CLUSTER_BASE    = Path("' + CLUSTER_BASE + '")',
    'MICROSTATES_DIR = CLUSTER_BASE / "microstates"',
    'FEATURES_DIR    = CLUSTER_BASE / "features"',
    'TARGETS_DIR     = CLUSTER_BASE / "targets"',
    'TSV_DIR         = Path("' + DIFUMO_ROOT + '")',
    'OUT_DIR         = CLUSTER_BASE / "results" / "network_proxy"',
    'OUT_DIR.mkdir(parents=True, exist_ok=True)',
    '',
    '# ── Config ───────────────────────────────────────────',
    'SUBJECTS     = ' + str(SUBJECTS_EEG_FMRI_ALL),
    'MISSING_RUNS = ' + str(MISSING_RUNS),
    'SFREQ_TAG    = "250Hz"',
    'RIDGE_ALPHA  = 1.0',
    'BASELINE_VOLS = 25',
    '',
    'DMN_PARCELS = ' + str(DMN_IDX),
    'CEN_PARCELS = ' + str(CEN_IDX),
    '',
    'TASK_RUNS = {',
    '    "rest":      ["01", "02"],',
    '    "shortrest": ["01"],',
    '    "feedback":  ["01", "02", "03", "04"],',
    '}',
    'FB_RUNS = ["01", "02", "03", "04"]',
    '',
    '# ── Microstate labels ────────────────────────────────',
    'asgn_path = MICROSTATES_DIR / ("assignments_" + SFREQ_TAG + ".json")',
    'with open(str(asgn_path)) as _f:',
    '    _asgn = json.load(_f)',
    'MS_LABELS = [_asgn.get(str(i), "MS" + str(i)) for i in range(7)]',
    'CEN_COL   = next(i for i, l in enumerate(MS_LABELS) if "CEN" in l.upper())',
    'DMN_COL   = next(i for i, l in enumerate(MS_LABELS) if "DMN" in l.upper())',
    'print("Labels:", MS_LABELS)',
    'print("CEN col:", CEN_COL, "  DMN col:", DMN_COL)',
    '',
    '# ── Helpers ──────────────────────────────────────────',
    'def baseline_zscore(x, n=25):',
    '    mu  = x[:n].mean(axis=0)',
    '    sig = x[:n].std(axis=0)',
    '    sig[sig < 1e-10] = 1e-10',
    '    return (x - mu) / sig',
    '',
    'def ridge_fit(X, y, alpha=1.0):',
    '    """Closed-form ridge regression weights (no intercept)."""',
    '    XtX = X.T @ X',
    '    return np.linalg.solve(XtX + alpha * np.eye(X.shape[1]), X.T @ y)',
    '',
    'def safe_r(a, b):',
    '    if len(a) < 3 or np.std(a) < 1e-10 or np.std(b) < 1e-10:',
    '        return float("nan")',
    '    return float(pearsonr(a, b)[0])',
    '',
    '# ── Load all data ────────────────────────────────────',
    'print()',
    'print("=" * 58)',
    'print("Loading data")',
    'print("=" * 58)',
    '',
    '# subj_data[subj] = list of (task, run, X, cen_p, dmn_p, cen_d, dmn_d, pda)',
    'subj_data = {}',
    '',
    'for subject in SUBJECTS:',
    '    print()',
    '    print("--- " + subject + " ---")',
    '    subj_data[subject] = []',
    '    for task, runs in TASK_RUNS.items():',
    '        for run in runs:',
    '            if subject in MISSING_RUNS:',
    '                if (task, run) in MISSING_RUNS[subject]:',
    '                    continue',
    '',
    '            feat_path = FEATURES_DIR / (subject + "_task-" + task',
    '                        + "_run-" + run + "_" + SFREQ_TAG + "_features.npy")',
    '            pda_path  = TARGETS_DIR  / (subject + "_task-" + task',
    '                        + "_run-" + run + "_pda_direct.npy")',
    '            cen_p_path = TARGETS_DIR / (subject + "_task-" + task',
    '                         + "_run-" + run + "_cen_z.npy")',
    '            dmn_p_path = TARGETS_DIR / (subject + "_task-" + task',
    '                         + "_run-" + run + "_dmn_z.npy")',
    '            tsv_path = TSV_DIR / (subject + "_ses-dmnelf_task-" + task',
    '                       + "_run-" + run + "_desc-difumo64_timeseries.tsv")',
    '',
    '            missing = [p.name for p in [feat_path, pda_path, cen_p_path,',
    '                        dmn_p_path, tsv_path] if not p.exists()]',
    '            if missing:',
    '                print("  SKIP " + task + " run-" + run',
    '                      + "  missing: " + str(missing))',
    '                continue',
    '',
    '            feats  = np.load(str(feat_path))          # (n_vols, 9)',
    '            pda    = np.load(str(pda_path)).astype(float)',
    '            cen_p  = np.load(str(cen_p_path)).astype(float)',
    '            dmn_p  = np.load(str(dmn_p_path)).astype(float)',
    '',
    '            # DiFuMo extraction — same logic as step 03',
    '            df       = pd.read_csv(str(tsv_path), sep="\\t")',
    '            roi_cols = ["ROI_" + str(i+1).zfill(2) for i in range(64)]',
    '            roi_z    = baseline_zscore(df[roi_cols].values.astype(float))',
    '            cen_d    = roi_z[:, CEN_PARCELS].mean(axis=1)',
    '            dmn_d    = roi_z[:, DMN_PARCELS].mean(axis=1)',
    '',
    '            # Align all to shortest',
    '            n = min(len(feats), len(pda), len(cen_p), len(dmn_p),',
    '                    len(cen_d), len(dmn_d))',
    '            X     = feats[:n, :7].astype(float)  # T-hat only',
    '            pda   = pda[:n]',
    '            cen_p = cen_p[:n]',
    '            dmn_p = dmn_p[:n]',
    '            cen_d = cen_d[:n]',
    '            dmn_d = dmn_d[:n]',
    '',
    '            subj_data[subject].append((task, run, X, cen_p, dmn_p, cen_d, dmn_d, pda))',
    '            print("  " + task + " run-" + run + "  n=" + str(n))',
    '',
    '# ── LORO CV (feedback runs) + all-run fit ─────────────',
    'print()',
    'print("=" * 58)',
    'print("LORO CV + interpretable fits")',
    'print("=" * 58)',
    '',
    'corr_rows   = []   # per-subject × run × source',
    'weight_rows = []   # per-subject × source: all-run weights',
    '',
    'for subject in SUBJECTS:',
    '    runs_all = subj_data.get(subject, [])',
    '    if not runs_all:',
    '        continue',
    '',
    '    fb_runs = [(t, r, X, cp, dp, cd, dd, pda)',
    '               for (t, r, X, cp, dp, cd, dd, pda) in runs_all',
    '               if t == "feedback"]',
    '    if not fb_runs:',
    '        print("  No feedback runs: " + subject)',
    '        continue',
    '',
    '    print()',
    '    print("--- " + subject + " ---")',
    '',
    '    # ── All-run fit for interpretable weights ─────────',
    '    X_all   = np.vstack([d[2] for d in fb_runs])',
    '    cen_p_all = np.concatenate([d[3] for d in fb_runs])',
    '    dmn_p_all = np.concatenate([d[4] for d in fb_runs])',
    '    cen_d_all = np.concatenate([d[5] for d in fb_runs])',
    '    dmn_d_all = np.concatenate([d[6] for d in fb_runs])',
    '',
    '    for src, cen_y, dmn_y in [',
    '            ("personal", cen_p_all, dmn_p_all),',
    '            ("difumo",   cen_d_all, dmn_d_all)]:',
    '        w_cen = ridge_fit(X_all, cen_y, RIDGE_ALPHA)',
    '        w_dmn = ridge_fit(X_all, dmn_y, RIDGE_ALPHA)',
    '        row = {"subject": subject, "source": src, "component": "w_CEN"}',
    '        for i, lbl in enumerate(MS_LABELS):',
    '            row["w_" + lbl] = round(float(w_cen[i]), 6)',
    '        weight_rows.append(row)',
    '        row = {"subject": subject, "source": src, "component": "w_DMN"}',
    '        for i, lbl in enumerate(MS_LABELS):',
    '            row["w_" + lbl] = round(float(w_dmn[i]), 6)',
    '        weight_rows.append(row)',
    '',
    '    # ── LORO CV ───────────────────────────────────────',
    '    for hold_idx, (task, run, X_te, cp_te, dp_te, cd_te, dd_te, pda_te) in enumerate(fb_runs):',
    '        train = [d for i, d in enumerate(fb_runs) if i != hold_idx]',
    '        if not train:',
    '            continue',
    '        X_tr    = np.vstack([d[2] for d in train])',
    '        cp_tr   = np.concatenate([d[3] for d in train])',
    '        dp_tr   = np.concatenate([d[4] for d in train])',
    '        cd_tr   = np.concatenate([d[5] for d in train])',
    '        dd_tr   = np.concatenate([d[6] for d in train])',
    '        pda_tr  = np.concatenate([d[7] for d in train])',
    '',
    '        row = {"subject": subject, "task": task, "run": run}',
    '',
    '        # Simple proxy baseline (no learning)',
    '        simple = X_te[:, CEN_COL] - X_te[:, DMN_COL]',
    '        row["r_simple"] = round(safe_r(simple, pda_te), 4)',
    '',
    '        for src, cen_tr, dmn_tr, cen_te, dmn_te in [',
    '                ("personal", cp_tr, dp_tr, cp_te, dp_te),',
    '                ("difumo",   cd_tr, dd_tr, cd_te, dd_te)]:',
    '            w_cen = ridge_fit(X_tr, cen_tr, RIDGE_ALPHA)',
    '            w_dmn = ridge_fit(X_tr, dmn_tr, RIDGE_ALPHA)',
    '            micro_cen = X_te @ w_cen',
    '            micro_dmn = X_te @ w_dmn',
    '            micro_pda = micro_cen - micro_dmn',
    '            row["r_microPDA_" + src]  = round(safe_r(micro_pda, pda_te), 4)',
    '            row["r_microCEN_" + src]  = round(safe_r(micro_cen, cen_te), 4)',
    '            row["r_microDMN_" + src]  = round(safe_r(micro_dmn, dmn_te), 4)',
    '',
    '        corr_rows.append(row)',
    '        print("  run-" + run',
    '              + "  r_simple="        + str(row["r_simple"])',
    '              + "  r_microPDA_pers=" + str(row.get("r_microPDA_personal", "?"))',
    '              + "  r_microPDA_dif="  + str(row.get("r_microPDA_difumo", "?")))',
    '',
    '# ── Transfer CV: train rest+shortrest → test feedback ─',
    'print()',
    'print("=" * 58)',
    'print("Transfer CV  (train: rest+shortrest  →  test: feedback)")',
    'print("=" * 58)',
    '',
    'transfer_rows = []',
    '',
    'for subject in SUBJECTS:',
    '    runs_all = subj_data.get(subject, [])',
    '    if not runs_all:',
    '        continue',
    '',
    '    rest_runs = [(t, r, X, cp, dp, cd, dd, pda)',
    '                 for (t, r, X, cp, dp, cd, dd, pda) in runs_all',
    '                 if t in ("rest", "shortrest")]',
    '    fb_runs   = [(t, r, X, cp, dp, cd, dd, pda)',
    '                 for (t, r, X, cp, dp, cd, dd, pda) in runs_all',
    '                 if t == "feedback"]',
    '',
    '    if not rest_runs or not fb_runs:',
    '        print("  SKIP " + subject + ": missing rest or feedback")',
    '        continue',
    '',
    '    print()',
    '    print("--- " + subject + " (transfer) ---")',
    '',
    '    X_tr    = np.vstack([d[2] for d in rest_runs])',
    '    cp_tr   = np.concatenate([d[3] for d in rest_runs])',
    '    dp_tr   = np.concatenate([d[4] for d in rest_runs])',
    '    cd_tr   = np.concatenate([d[5] for d in rest_runs])',
    '    dd_tr   = np.concatenate([d[6] for d in rest_runs])',
    '',
    '    # Train once on all rest+shortrest',
    '    models = {}',
    '    for src, cen_tr, dmn_tr in [("personal", cp_tr, dp_tr),',
    '                                 ("difumo",   cd_tr, dd_tr)]:',
    '        models[src] = (',
    '            ridge_fit(X_tr, cen_tr, RIDGE_ALPHA),',
    '            ridge_fit(X_tr, dmn_tr, RIDGE_ALPHA),',
    '        )',
    '',
    '    # Test on each feedback run',
    '    for task, run, X_te, cp_te, dp_te, cd_te, dd_te, pda_te in fb_runs:',
    '        row = {"subject": subject, "task": task, "run": run}',
    '        row["r_simple"] = round(safe_r(',
    '            X_te[:, CEN_COL] - X_te[:, DMN_COL], pda_te), 4)',
    '        for src, cen_te, dmn_te in [("personal", cp_te, dp_te),',
    '                                     ("difumo",   cd_te, dd_te)]:',
    '            w_cen, w_dmn = models[src]',
    '            micro_pda = X_te @ w_cen - X_te @ w_dmn',
    '            row["r_microPDA_" + src]  = round(safe_r(micro_pda, pda_te), 4)',
    '            row["r_microCEN_" + src]  = round(safe_r(X_te @ w_cen, cen_te), 4)',
    '            row["r_microDMN_" + src]  = round(safe_r(X_te @ w_dmn, dmn_te), 4)',
    '        transfer_rows.append(row)',
    '        print("  fb run-" + run',
    '              + "  r_simple="        + str(row["r_simple"])',
    '              + "  r_pers="          + str(row.get("r_microPDA_personal", "?"))',
    '              + "  r_difu="          + str(row.get("r_microPDA_difumo", "?")))',
    '',
    '# ── Save CSVs ─────────────────────────────────────────',
    'def write_csv(path, rows):',
    '    if not rows: return',
    '    seen = {}',
    '    for r in rows:',
    '        for k in r: seen[k] = None',
    '    fields = list(seen.keys())',
    '    with open(str(path), "w", newline="") as f:',
    '        w = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")',
    '        w.writeheader(); w.writerows(rows)',
    '    print("  " + path.name)',
    '',
    'write_csv(OUT_DIR / "network_proxy_correlations_250Hz.csv",  corr_rows)',
    'write_csv(OUT_DIR / "network_proxy_transfer_250Hz.csv",      transfer_rows)',
    'write_csv(OUT_DIR / "network_proxy_weights_250Hz.csv",       weight_rows)',
    '',
    '# ── Group figure ──────────────────────────────────────',
    'print()',
    'print("=" * 58)',
    'print("Generating group figure")',
    'print("=" * 58)',
    '',
    'N_MS = len(MS_LABELS)',
    'C_PERS = "#5080D0"',
    'C_DIFU = "#E07020"',
    '',
    '# Group-mean weights: average w_CEN and w_DMN across subjects',
    'def group_weights(component, source):',
    '    vecs = []',
    '    for r in weight_rows:',
    '        if r["component"] == component and r["source"] == source:',
    '            vecs.append([r["w_" + lbl] for lbl in MS_LABELS])',
    '    if not vecs: return np.full(N_MS, float("nan"))',
    '    return np.mean(vecs, axis=0)',
    '',
    'wc_pers = group_weights("w_CEN", "personal")',
    'wd_pers = group_weights("w_DMN", "personal")',
    'wc_difu = group_weights("w_CEN", "difumo")',
    'wd_difu = group_weights("w_DMN", "difumo")',
    '',
    '# LORO correlation summary per subject (mean across feedback runs)',
    'def subj_mean_r(col):',
    '    sm = {}',
    '    for r in corr_rows:',
    '        s = r["subject"]',
    '        v = r.get(col, float("nan"))',
    '        if v == v:',
    '            sm.setdefault(s, []).append(v)',
    '    return [np.mean(vs) for vs in sm.values() if vs]',
    '',
    'r_simple   = subj_mean_r("r_simple")',
    'r_pda_pers = subj_mean_r("r_microPDA_personal")',
    'r_pda_difu = subj_mean_r("r_microPDA_difumo")',
    '',
    'fig, axes = plt.subplots(2, 2, figsize=(16, 10))',
    'fig.suptitle("Decomposed microstate network proxy: microCEN − microDMN = microPDA\\n"',
    '             "Personal masks vs DiFuMo group parcels — LORO CV (feedback runs)",',
    '             fontsize=11, fontweight="bold")',
    '',
    'x = np.arange(N_MS)',
    'w_bar = 0.38',
    '',
    '# ── Panel A: w_CEN weights ────────────────────────────',
    'ax = axes[0, 0]',
    'ax.bar(x - w_bar/2, wc_pers, w_bar, color=C_PERS, alpha=0.8, label="personal")',
    'ax.bar(x + w_bar/2, wc_difu, w_bar, color=C_DIFU, alpha=0.8, label="DiFuMo")',
    'ax.axhline(0, color="black", lw=0.8, ls="--")',
    'ax.set_xticks(x); ax.set_xticklabels(MS_LABELS, fontsize=10)',
    'ax.set_ylabel("Ridge weight (group mean)", fontsize=10)',
    'ax.set_title("A   w_CEN  (T-hat → CEN_z)", fontsize=11, fontweight="bold")',
    'ax.legend(fontsize=9)',
    '',
    '# ── Panel B: w_DMN weights ────────────────────────────',
    'ax = axes[0, 1]',
    'ax.bar(x - w_bar/2, wd_pers, w_bar, color=C_PERS, alpha=0.8, label="personal")',
    'ax.bar(x + w_bar/2, wd_difu, w_bar, color=C_DIFU, alpha=0.8, label="DiFuMo")',
    'ax.axhline(0, color="black", lw=0.8, ls="--")',
    'ax.set_xticks(x); ax.set_xticklabels(MS_LABELS, fontsize=10)',
    'ax.set_ylabel("Ridge weight (group mean)", fontsize=10)',
    'ax.set_title("B   w_DMN  (T-hat → DMN_z)", fontsize=11, fontweight="bold")',
    'ax.legend(fontsize=9)',
    '',
    '# ── Panel C: LORO r comparison ────────────────────────',
    'ax = axes[1, 0]',
    'labels_c   = ["simple\\n(CEN−DMN)", "microPDA\\n(personal)", "microPDA\\n(DiFuMo)"]',
    'vals_c     = [r_simple, r_pda_pers, r_pda_difu]',
    'colors_c   = ["#888888", C_PERS, C_DIFU]',
    'jitter_rng = np.random.default_rng(42)',
    'for ci, (lbl, vals, col) in enumerate(zip(labels_c, vals_c, colors_c)):',
    '    if not vals: continue',
    '    jit = jitter_rng.uniform(-0.08, 0.08, len(vals))',
    '    ax.scatter(np.full(len(vals), ci) + jit, vals, color=col, alpha=0.7, s=50, zorder=3)',
    '    m = float(np.mean(vals))',
    '    se = float(np.std(vals, ddof=1) / np.sqrt(len(vals))) if len(vals) > 1 else 0',
    '    ax.errorbar(ci, m, yerr=se, fmt="D", color=col, markersize=10,',
    '                capsize=6, lw=2.2, zorder=5)',
    'ax.axhline(0, color="black", lw=0.8, ls="--")',
    'ax.set_xticks(range(len(labels_c)))',
    'ax.set_xticklabels(labels_c, fontsize=10)',
    'ax.set_ylabel("Pearson r  (microPDA vs pda_direct)", fontsize=10)',
    'ax.set_title("C   LORO CV — feedback runs (per subject mean)", fontsize=11, fontweight="bold")',
    '',
    '# ── Panel D: personal vs DiFuMo scatter ──────────────',
    'ax = axes[1, 1]',
    'subj_keys = sorted(set(r["subject"] for r in corr_rows))',
    'for r in corr_rows:',
    '    ax.scatter(r.get("r_microPDA_personal", float("nan")),',
    '               r.get("r_microPDA_difumo",   float("nan")),',
    '               color="#888888", alpha=0.55, s=30)',
    '_lim = max(abs(v) for vs in [r_pda_pers, r_pda_difu] for v in vs) * 1.2 if (r_pda_pers or r_pda_difu) else 0.5',
    'ax.plot([-_lim, _lim], [-_lim, _lim], "k--", lw=0.8)',
    'ax.axhline(0, color="black", lw=0.5, ls="--")',
    'ax.axvline(0, color="black", lw=0.5, ls="--")',
    'ax.set_xlabel("r_microPDA (personal)", fontsize=10)',
    'ax.set_ylabel("r_microPDA (DiFuMo)", fontsize=10)',
    'ax.set_title("D   Personal vs DiFuMo (run-level)", fontsize=11, fontweight="bold")',
    '',
    'plt.tight_layout()',
    'fig_path = OUT_DIR / "network_proxy_group_250Hz.png"',
    'plt.savefig(str(fig_path), dpi=150, bbox_inches="tight")',
    'plt.close(fig)',
    'print("  " + fig_path.name)',
    '',
    '# ── Transfer figure ───────────────────────────────────',
    'print()',
    'print("=" * 58)',
    'print("Generating transfer figure")',
    'print("=" * 58)',
    '',
    'def subj_mean_r_from(rows, col):',
    '    sm = {}',
    '    for r in rows:',
    '        s = r["subject"]',
    '        v = r.get(col, float("nan"))',
    '        if v == v:',
    '            sm.setdefault(s, []).append(v)',
    '    return [np.mean(vs) for vs in sm.values() if vs]',
    '',
    'tr_simple   = subj_mean_r_from(transfer_rows, "r_simple")',
    'tr_pda_pers = subj_mean_r_from(transfer_rows, "r_microPDA_personal")',
    'tr_pda_difu = subj_mean_r_from(transfer_rows, "r_microPDA_difumo")',
    '',
    'fig2, axes2 = plt.subplots(1, 2, figsize=(14, 5))',
    'fig2.suptitle("Transfer CV: train rest+shortrest  →  test feedback\\n"',
    '              "microCEN − microDMN = microPDA  (per subject mean ± SE)",',
    '              fontsize=11, fontweight="bold")',
    '',
    '# ── Panel A: strip + mean comparison ─────────────────',
    'ax = axes2[0]',
    'labels_t = ["simple\\n(CEN−DMN)", "microPDA\\n(personal)", "microPDA\\n(DiFuMo)"]',
    'vals_t   = [tr_simple, tr_pda_pers, tr_pda_difu]',
    'cols_t   = ["#888888", C_PERS, C_DIFU]',
    'jrng = np.random.default_rng(0)',
    'for ci, (lbl, vals, col) in enumerate(zip(labels_t, vals_t, cols_t)):',
    '    if not vals: continue',
    '    jit = jrng.uniform(-0.08, 0.08, len(vals))',
    '    ax.scatter(np.full(len(vals), ci) + jit, vals,',
    '               color=col, alpha=0.75, s=60, zorder=3)',
    '    m  = float(np.mean(vals))',
    '    se = float(np.std(vals, ddof=1) / np.sqrt(len(vals))) if len(vals) > 1 else 0',
    '    ax.errorbar(ci, m, yerr=se, fmt="D", color=col,',
    '                markersize=11, capsize=6, lw=2.4, zorder=5)',
    'ax.axhline(0, color="black", lw=0.8, ls="--")',
    'ax.set_xticks(range(len(labels_t)))',
    'ax.set_xticklabels(labels_t, fontsize=11)',
    'ax.set_ylabel("Pearson r  (microPDA vs pda_direct)", fontsize=10)',
    'ax.set_title("A   Group comparison", fontsize=11, fontweight="bold")',
    '',
    '# ── Panel B: per-run scatter coloured by subject ──────',
    'ax = axes2[1]',
    '_subjs = sorted(set(r["subject"] for r in transfer_rows))',
    '_cmap  = plt.cm.get_cmap("tab10", len(_subjs))',
    '_sidx  = {s: i for i, s in enumerate(_subjs)}',
    'for r in transfer_rows:',
    '    col = _cmap(_sidx[r["subject"]])',
    '    ax.scatter(r.get("r_microPDA_personal", float("nan")),',
    '               r.get("r_microPDA_difumo",   float("nan")),',
    '               color=col, alpha=0.7, s=40)',
    '_all_v = [v for r in transfer_rows',
    '          for k in ["r_microPDA_personal", "r_microPDA_difumo"]',
    '          for v in [r.get(k, float("nan"))] if v == v]',
    '_lim2 = max(abs(v) for v in _all_v) * 1.2 if _all_v else 0.5',
    'ax.plot([-_lim2, _lim2], [-_lim2, _lim2], "k--", lw=0.8)',
    'ax.axhline(0, color="black", lw=0.5, ls="--")',
    'ax.axvline(0, color="black", lw=0.5, ls="--")',
    'ax.set_xlabel("r_microPDA (personal)", fontsize=10)',
    'ax.set_ylabel("r_microPDA (DiFuMo)",   fontsize=10)',
    'ax.set_title("B   Personal vs DiFuMo (each feedback run)", fontsize=11, fontweight="bold")',
    '',
    'from matplotlib.lines import Line2D',
    'ax.legend([Line2D([0],[0], marker="o", color="w",',
    '           markerfacecolor=_cmap(i), markersize=8)',
    '           for i in range(len(_subjs))],',
    '          [s.replace("sub-dmnelf","s") for s in _subjs],',
    '          fontsize=7, loc="upper left")',
    '',
    'plt.tight_layout()',
    'fig2_path = OUT_DIR / "network_proxy_transfer_250Hz.png"',
    'plt.savefig(str(fig2_path), dpi=150, bbox_inches="tight")',
    'plt.close(fig2)',
    'print("  " + fig2_path.name)',
    '',
    'print()',
    'print("=" * 58)',
    'print("DONE")',
    'print("=" * 58)',
]

# ── Save cluster script ─────────────────────────────────────────
script_name = "07_microstate_network_proxy_cluster.py"
script_path = LOCAL_BASE / "scripts" / script_name
script_path.parent.mkdir(parents=True, exist_ok=True)

with open(script_path, "w") as f:
    f.write("\n".join(lines))

# ── Syntax check ───────────────────────────────────────────────
print("Checking syntax...")
try:
    py_compile.compile(str(script_path), doraise=True)
    print("Syntax OK: " + script_name)
except py_compile.PyCompileError as e:
    print("SYNTAX ERROR: " + str(e))
    raise

# ── SLURM script ───────────────────────────────────────────────
job_name    = "ms_network_proxy"
sbatch_name = "07_microstate_network_proxy.sh"
sbatch_path = LOCAL_BASE / "scripts" / sbatch_name

sbatch_lines = [
    "#!/bin/bash",
    "#SBATCH --job-name=" + job_name,
    "#SBATCH --output=" + CLUSTER_BASE + "/logs/" + job_name + "_%j.out",
    "#SBATCH --error="  + CLUSTER_BASE + "/logs/" + job_name + "_%j.err",
    "#SBATCH --partition=short",
    "#SBATCH --time=00:30:00",
    "#SBATCH --cpus-per-task=2",
    "#SBATCH --mem=8G",
    "#SBATCH --account=" + SLURM_ACCOUNT,
    "",
    PYTHON + " " + CLUSTER_BASE + "/scripts/" + script_name,
]

with open(sbatch_path, "w") as f:
    f.write("\n".join(sbatch_lines))

# ── Deploy ─────────────────────────────────────────────────────
print("\nDeploying...")
scp_to(script_path,
       CLUSTER_BASE + "/scripts/" + script_name,
       verbose=False)
scp_to(sbatch_path,
       CLUSTER_BASE + "/scripts/" + sbatch_name,
       verbose=False)
print("Deployed: " + script_name)

# ── Submit ─────────────────────────────────────────────────────
print("\nSubmitting SLURM job...")
result = run_ssh("sbatch " + CLUSTER_BASE + "/scripts/" + sbatch_name)
job_id = ""
for line in result.stdout.strip().split("\n"):
    if "Submitted" in line:
        job_id = line.strip().split()[-1]
        print("Job ID: " + job_id)

# ── Monitor ────────────────────────────────────────────────────
if job_id:
    print("\nMonitoring job " + job_id + "  (Ctrl+C to stop)")
    print("-" * 58)
    try:
        while True:
            r = run_ssh(
                "squeue -j " + job_id
                + " --format=%.8i_%.8T_%.10M 2>/dev/null",
                verbose=False
            )
            status = r.stdout.strip()
            if status and "JOBID" not in status.split("\n")[-1]:
                print(status)
            else:
                print("Job finished — checking log...")
                log = run_ssh(
                    "tail -40 " + CLUSTER_BASE
                    + "/logs/" + job_name + "_" + job_id
                    + ".out 2>/dev/null",
                    verbose=False
                )
                print(log.stdout)
                break
            time.sleep(20)
    except KeyboardInterrupt:
        print("\nStopped watching.")
        print("  tail -f " + CLUSTER_BASE
              + "/logs/" + job_name + "_" + job_id + ".out")
