data:
  fmriprep_dir: /projects/swglab/data/rtBPD/derivatives/fmriprep_25.2.5_fmap
  features_dir: /projects/swglab/data/rtBPD/derivatives/cyclic_features
  eeg_preproc_dir: /projects/swglab/data/rtBPD/derivatives/eeg_preprocessed
  masks_dir: /projects/swglab/data/rtBPD/derivatives/network_masks
  session: ses-nf1
  session_eeg: ses-nf
  task: feedback

  subjects:
    all: [rtbpd002, rtbpd003, rtbpd004]

  fmri:
    tr: 1.2
    space: MNI152NLin6Asym
    res: 2
    dmn_idx: 64
    cen_idx: 65
    n_difumo: 64

  eeg:
    sfreq: 500.0
    samples_per_tr: 600
    desc: preproc500Hz

  confounds:
    - trans_x
    - trans_y
    - trans_z
    - rot_x
    - rot_y
    - rot_z
    - white_matter
    - csf
